---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: extensions-backend-secrets
  namespace: aaron-extensions-preprod
spec:
  encryptedData:
    CHASTER_API_TOKEN: AgASgelurAV4xsVodOmZQwn2vTmL+1tDBCDpnZeY+E4+flB5UubgNUR6wQrP6A8y+3l7gly29/uuZ+cWlswEJZXEzMkJz2Tw3xaY2kuLesrNjSxxz+nt0yQkjMlzD3BHSPp9MpWzFHkmjAEFwwD7ZHBI1hU8TodpFNi/vh+irXvEbLJUvJRDyit+vaLtjPBlbWtRFaJM8G33g2KWJ8GSQT7lnuGuyMxINCwsQP6sFv/3J8vl3tOnWxWwKpTj0fb7ZfEymluGBDZGsH9Pnjcy3yza3YYr6ES19p15InrfIjVC8+P620YdUbUXr3SPL4nmEmfYOTM5UcGlqzUWnwcn8gNvzhXSfMlhy8IdKGxDQKw3GIq8uvjzxv9ljsGGtFa4KeHLvmbv9LrHYq+baJfBEhdKmZxR62p1w58QiIufPQX2h84o4ipRMyLRNIj8sFfrWpehRS6zgbRjuTqsKov0fvnHw1sjcBVW2Bc8r/U49B2cvpTg00STeWqkKkUkV+OYkrQh5WbJVROpVa/6PpMGDQMWNaz2aFUedRlLvwvq4i3qUnwOf57benpelUd/yz75hp5t0dOYleke42txdS/TSBzzbFICS1zm46hAOf1gXxPBh4BO2nQ5WVn0XrVffU+u1wHkN8kfG8FWzKR1U6RJBXmEUYRWjCImW6/p8YFGm11AiIgGFrDjYF9uRjJV3q476M4xyU8XtT47qNs/w8Xv6IeQkiRaNP6VBDTV/H1IuTZCEQ==
    DATABASE_URL: AgBZ0XEKLCzxMesnSO9oscpT7XxcmrIb3SO9jewftcoiI/w3YtcGhuTHJ0Nz3o9hjdN1q+UEB0EpUK5t7K88rlgDhnZfWzy5kYAfruu18O2kFZGD0WHBC/l/J2b1+Y2I3eMxKbscs7FA8gcxC9gNai4EOhy/ngK/yxqr73vStynogIyOu2gcPyCXQJON+TJUOCf/UGtuZ1QuCMp5JE6ew7/AcyGjNo2AtwP3o0/U9tRBODytw2oHDeOEsI7bdGjUddnXisy4BAGD1aOcAvh/o/TSRDyc+kD6BWTY6+4WVBViQivceRF8D8ncMJT6tJicmfvyxDeIeSKIzD20QrkSg9ISmMrl0n8KFJEp/qlR+UtTl7RGYUkJaWq5sv0EWzqhLaDW8CrJ+eI3gM1tEX+1JBokWJMP8GFkWulHwxiXQYIRM1OXyQW8SZmAOYo6C5BtWGJxFZaun4RPiVyDTNXXJyK9w4ZquJTC+155Tmpr7JOVGmGD98GRTe6jDDxeoHSQCRlo1iVMNhJj9wvf2QGJftQHtCIp8rW9oSaSDDZ/Uf78gsIYC63fITkyYx39VR/awFAqr+crVzowMNsW51WQ42wxbX+WGZgl070u2cPlCAGn4vgXUI0uNHjssXa7mh5Y0Hl8eN0U9fQhPD6UolYJKHRSHtpgIlaL/AE256B1qsNT0S8tvOLjNSSqu3BYO/g9nwwiB4J5c2rCYeygTzBSbZJrTX/kkgq3kPvN9ZsoA+jMRgT4VPJNsnoyytlFI4/0KkI4dyj1SdZE+OqAGvbtS5aPr91Ltpd/vSTObCdaUpVQT8/F+nc0wgsJ8TkrsDFagULDTsqhBVpEil8gC186/tKJYWV9cywpJ5ktpck9q3dEIcVExESC4Jvt8F6bFR3NxIwaCJMn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: extensions-backend-secrets
      namespace: aaron-extensions-preprod
