replicaCount: 2

image:
  repository: ghcr.io/chasterapp/chaster-extensions
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ghcr-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: "extensions.chaster.app"
  path: /
  pathType: ImplementationSpecific

resources: {}
