name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/chasterapp/chaster-extensions
        tags: |
          type=ref,event=branch
          type=sha,format=long

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to image repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  unit-test:
    name: Run Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:ci

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-report
        path: coverage/lcov-report/
        retention-days: 30

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: junit.xml

  e2e-test:
    name: Run E2E Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Copy environment variables
      run: cp .env.sample .env

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test:e2e

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: junit-playwright.xml

  deploy-preprod:
    name: Deploy to preprod
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl
    env:
      KUBECONFIG: "/tmp/config"
    steps:
    - name: Checkout main
      uses: actions/checkout@v3

    - name: Export Kubernetes secret
      run: echo "${{ secrets.K8S_KUBECONFIG }}" > /tmp/config

    - name: Deploy on environment
      run: ./k8s/deploy.sh preprod sha-${{ github.sha }}

  notify:
    name: Notify build
    timeout-minutes: 5
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, unit-test, e2e-test, deploy-preprod]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run notification script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: ./.github/notify-discord.sh ${{ needs.build.result }} ${{ needs.unit-test.result }} ${{ needs.e2e-test.result }} ${{ needs.deploy-preprod.result }} ${{ github.sha }} ${{ github.run_id }}
